/* eslint-disable max-len */
/* eslint-disable import/prefer-default-export */
export const exerciseInfo = [
    {
        name: 'Around The World',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/around-the-world/49351301-Around-the-World-Superman_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Face Pull',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/band-face-pull/08961301-Band-face-pull_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Band Pull Apart',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/band-pull-apart/45681301-Resistance-Band-Pull-Apart_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bear Crawl',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bear-crawl/33601301-Bear-Crawl_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bent Over Row',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bent-over-rows/45701301-Resistance-Band-Bent-Over-Neutral-Grip-Row_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bodyweight Row',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bodyweight-row/31651301-Bodyweight-Standing-Row-(with-towel)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Chin Tuck',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/chin-tuck/31491301-Chin-Tuck_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Donkey Kick',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/donkey-kick/63161301-Basic-to-Cross-Donkey-Kick-(female)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Face Pull - Sitting',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/face-pull-feet-band/44451301-Resistance-Band-Seated-Face-Pull_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Front Plank Arm Lift Hold',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/front-plank-arm-lift/28941301-Front-Plank-with-Arm-Lift-(female)_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Front Plank Arm and Leg Lift',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/front-plank-leg-lift/28961301-Front-Plank-with-Arm-and-Leg-Lift-(female)_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Front Plank Leg Lift',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/front-plank-lift/35011301-Front-Plank-with-Leg-Lift-(male)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Plank',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/front-plank/23471301-Front-Plank---Butt-(WRONG-RIGHT)_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Glute Bridge On Heels',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/heel-glute-bridge/64351301-Heel-Glute-Bridge-(female)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'High Plank',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/high-plank/51591301-Plank-on-Hands_Waist_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Plank With Hip Roll',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/hip-roll-plank/43851301-Hip-Roll-Plank_Waist_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Kneeling Face Pull',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/kneeling-face-pull/41951301-Resistance-Band-Half-Kneeling-Face-Pull_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Lying Chin Tuck',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lying-chin-tuck/50621301-Lying-Chin-Tucks_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Lying Scissor Kick',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lying-scissor-kick/06221301-Lying-Scissor-Kick_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    // {
    //     name: 'Lying T-Raise',
    //     description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
    //     image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lying-t-raise/48321301-Lying-Rear-Lateral-Raise_Shoulders_720.gif',
    //     video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
    //     required: true,
    //     muscleGroup: 'back',
    //     equipmentNeeded: ['none'],
    // },
    {
        name: 'Lying T-Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lying-t-raise/48321301-Lying-Rear-Lateral-Raise_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Plank Alternating Arm Lift',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/plank-arm-lift/14401301-Plank-arm-lifts_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Prone Y-Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/proe-y/58001301-Bodyweight-Lying-Prone-Ys_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Prone Cervical Extension Hold',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-cercical-ext-hold/50611301-Prone-Cervical-Extension-Isometric-Hold_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Prone T-Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-t-raise/50411301-Lying-Prone-T_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Prone Y-Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-y-raise/58221301-Prone-Y-Raise-(male)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Push Up Plus',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/push-up-plus/31451301-Push-Up-Plus_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Scapular Push Up',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/scap-pushup/41171301-Kneeling-Scapular-Push-Up-(male)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Wall Slide',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/serratus-wall-slide/50251301-Serratus-Wall-Slide_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Side Plank',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/side-plank/07151301-Side-Plank-(male)_Waist-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Single Leg Glute Bridge',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/single-leg-glute-bridge/60001301-Single-Leg-Bridge-with-Outstretched-Leg-(left)-(male)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Single Leg Glute Bridge Hold',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/single-leg-glute-bridge-female/60011301-Single-Straight-Leg-Glute-Bridge-Hold-(left)-(female)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Superman W-Raise Leg Lift',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/superman-w-leg-lift/50491301-Superman-W_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Superman W/Y Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/superman-w-y/50481301-Superman-W-to-Y_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Superman',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/superman-waist/08041301-Superman_Waist_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Swimming',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/swimming/28701301-Swimming_Pilates_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
];

/* eslint-disable import/prefer-default-export */
export const stretchInfo = [
    {
        name: 'Cobra Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cobra/14821301-Cobra-Yoga-Pose_Stretching-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Down Dog',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/down-dog/34691301-Downward-Facing-Dog_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Child Pose',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/child-pose/09451301-Child-Pose-(female)_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Circles',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/neck-circle/39941301-Neck-Circle-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Circles',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/neck-circle/39941301-Neck-Circle-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Extension',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/neck-extension-stretch/18441301-Extension-And-Inclination-Neck-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Flexor',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/neck-flexor-stretch/18401301-Neck-Flexor-And-Rotational-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bent Over Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bent-over-pec-stretch/45151301-Back-Pec-Stretch_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Doorway Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/doorway-pec-stretch/55571301-Standing-Chest-Stretch-against-Door_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Elbows Back Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/elbows-back-stretch/46721301-Elbows-Back-Stretch-(male)_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Happy Baby',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/happy-baby/59171301-Happy-Baby-Pose-(female)_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Dead Hang',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/dead-hang/50551301-Dead-Hang-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Cat Cow',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cat-cow/45801301-Cat-Cow-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Cat Cow',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cat-cow/45801301-Cat-Cow-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Diagonal Neck Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/diagonal-neck-stretch/18321301-Diagonal-Flexion-Neck-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Foam Roll - Rotation',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/foam-roll-kneeling-rotation/53881301-Roll-Kneeling-Upper-Back-Rotation_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Foam Roll With Rotation',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/foam-roll-kneeling-rotation/53881301-Roll-Kneeling-Upper-Back-Rotation_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Foam Roll',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/foam-roll/53821301-Roll-Middle-Back-Lying-on-Floor_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Hip Flexor Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/hip-flexor-stretch/46741301-Hip-Flexor-Stretch-Rear-foot-elevated-(male)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Kneeling Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/kneeling-chest-stretch/17851301-Kneeling-Chest-Stretch_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'One Arm Lat Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lat-stretc/18011301-One-arm-Lat-Stretch_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Pigeon',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/pigeon/19431301-Pigeon-Hip-Stretch_Hips-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Reverse Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/reverse-chest-stretch/17821301-Reverse-Chest-Stretch_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Seated Neck Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/seated-neck-stretch/51951301-Seated-Neck-Side-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Side Neck Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/side-neck-stretch/07131301-Side-Neck-Stretch_Neck-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Straight Arm Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/straight-arm-chest-stretch/65401301-Big-Turn-Back-Stretch-(female)_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Thoracic Rotation',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/thoracic-rotation/42971301--Kneeling-Back-Rotation-Stretch-(female)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Thoracic Stretch - Foam Roller',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/thoracic-stretch-foam-roll/54231301-Roll-Thoracic-Spine-Lying-on-Floor-(female)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Toe Touch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/touch-toes/43131301-Spine-Stretch-(female)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },

];

export const exerciseStretchCombo = [
    {
        name: 'Cobra Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cobra/14821301-Cobra-Yoga-Pose_Stretching-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Down Dog',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/down-dog/34691301-Downward-Facing-Dog_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Child Pose',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/child-pose/09451301-Child-Pose-(female)_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Circles',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/neck-circle/39941301-Neck-Circle-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Circles',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/neck-circle/39941301-Neck-Circle-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Extension',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/neck-extension-stretch/18441301-Extension-And-Inclination-Neck-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Flexor',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/neck-flexor-stretch/18401301-Neck-Flexor-And-Rotational-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bent Over Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bent-over-pec-stretch/45151301-Back-Pec-Stretch_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Doorway Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/doorway-pec-stretch/55571301-Standing-Chest-Stretch-against-Door_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Elbows Back Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/elbows-back-stretch/46721301-Elbows-Back-Stretch-(male)_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Happy Baby',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/happy-baby/59171301-Happy-Baby-Pose-(female)_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Dead Hang',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/dead-hang/50551301-Dead-Hang-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Cat Cow',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cat-cow/45801301-Cat-Cow-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Cat Cow',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cat-cow/45801301-Cat-Cow-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Diagonal Neck Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/diagonal-neck-stretch/18321301-Diagonal-Flexion-Neck-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Foam Roll - Rotation',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/foam-roll-kneeling-rotation/53881301-Roll-Kneeling-Upper-Back-Rotation_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Foam Roll With Rotation',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/foam-roll-kneeling-rotation/53881301-Roll-Kneeling-Upper-Back-Rotation_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Foam Roll',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/foam-roll/53821301-Roll-Middle-Back-Lying-on-Floor_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Hip Flexor Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/hip-flexor-stretch/46741301-Hip-Flexor-Stretch-Rear-foot-elevated-(male)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Kneeling Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/kneeling-chest-stretch/17851301-Kneeling-Chest-Stretch_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'One Arm Lat Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lat-stretc/18011301-One-arm-Lat-Stretch_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Pigeon',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/pigeon/19431301-Pigeon-Hip-Stretch_Hips-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Reverse Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/reverse-chest-stretch/17821301-Reverse-Chest-Stretch_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Seated Neck Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/seated-neck-stretch/51951301-Seated-Neck-Side-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Side Neck Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/side-neck-stretch/07131301-Side-Neck-Stretch_Neck-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Straight Arm Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/straight-arm-chest-stretch/65401301-Big-Turn-Back-Stretch-(female)_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Thoracic Rotation',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/thoracic-rotation/42971301--Kneeling-Back-Rotation-Stretch-(female)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Thoracic Stretch - Foam Roller',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/thoracic-stretch-foam-roll/54231301-Roll-Thoracic-Spine-Lying-on-Floor-(female)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Toe Touch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/touch-toes/43131301-Spine-Stretch-(female)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Around The World',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/around-the-world/49351301-Around-the-World-Superman_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Assisted Chin Tuck',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/assisted-chin-tuck/31501301-Assisted-Chin-Tuck_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Face Pull',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/band-face-pull/08961301-Band-face-pull_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Band Pull Apart',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/band-pull-apart/45681301-Resistance-Band-Pull-Apart_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bear Crawl',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bear-crawl/33601301-Bear-Crawl_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bent Over Row',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bent-over-rows/45701301-Resistance-Band-Bent-Over-Neutral-Grip-Row_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bodyweight Row',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bodyweight-row/31651301-Bodyweight-Standing-Row-(with-towel)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Chin Tuck',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/chin-tuck/31491301-Chin-Tuck_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Donkey Kick',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/donkey-kick/63161301-Basic-to-Cross-Donkey-Kick-(female)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Face Pull - Sitting',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/face-pull-feet-band/44451301-Resistance-Band-Seated-Face-Pull_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Front Plank Arm Lift Hold',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/front-plank-arm-lift/28941301-Front-Plank-with-Arm-Lift-(female)_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Front Plank Arm and Leg Lift',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/front-plank-leg-lift/28961301-Front-Plank-with-Arm-and-Leg-Lift-(female)_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Front Plank Leg Lift',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/front-plank-lift/35011301-Front-Plank-with-Leg-Lift-(male)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Plank',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/front-plank/23471301-Front-Plank---Butt-(WRONG-RIGHT)_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Glute Bridge On Heels',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/heel-glute-bridge/64351301-Heel-Glute-Bridge-(female)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'High Plank',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/high-plank/51591301-Plank-on-Hands_Waist_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Plank With Hip Roll',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/hip-roll-plank/43851301-Hip-Roll-Plank_Waist_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Kneeling Face Pull',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/kneeling-face-pull/41951301-Resistance-Band-Half-Kneeling-Face-Pull_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Lying Chin Tuck',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lying-chin-tuck/50621301-Lying-Chin-Tucks_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Lying Scissor Kick',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lying-scissor-kick/06221301-Lying-Scissor-Kick_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Lying T-Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lying-t-raise/48321301-Lying-Rear-Lateral-Raise_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Lying T-Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lying-t-raise/48321301-Lying-Rear-Lateral-Raise_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Plank Alternating Arm Lift',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/plank-arm-lift/14401301-Plank-arm-lifts_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Prone Y-Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/proe-y/58001301-Bodyweight-Lying-Prone-Ys_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Prone Cervical Extension Hold',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-cercical-ext-hold/50611301-Prone-Cervical-Extension-Isometric-Hold_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Prone T-Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-t-raise/50411301-Lying-Prone-T_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Prone Y-Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-y-raise/58221301-Prone-Y-Raise-(male)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Push Up Plus',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/push-up-plus/31451301-Push-Up-Plus_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Scapular Push Up',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/scap-pushup/41171301-Kneeling-Scapular-Push-Up-(male)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Wall Slide',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/serratus-wall-slide/50251301-Serratus-Wall-Slide_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Side Plank',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/side-plank/07151301-Side-Plank-(male)_Waist-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Single Leg Glute Bridge',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/single-leg-glute-bridge/60001301-Single-Leg-Bridge-with-Outstretched-Leg-(left)-(male)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Single Leg Glute Bridge Hold',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/single-leg-glute-bridge-female/60011301-Single-Straight-Leg-Glute-Bridge-Hold-(left)-(female)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Superman W-Raise Leg Lift',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/superman-w-leg-lift/50491301-Superman-W_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Superman W/Y Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/superman-w-y/50481301-Superman-W-to-Y_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Superman',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/superman-waist/08041301-Superman_Waist_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Swimming',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/swimming/28701301-Swimming_Pilates_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
];
