/* eslint-disable import/prefer-default-export */
export const exerciseInfo = [
    {
        name: 'Chest Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/doorway-pec-stretch/55571301-Standing-Chest-Stretch-against-Door_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Chest Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'chest',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Chest Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'chest',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Chest Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'chest',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Chest Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'chest',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Core Stretch 1',
        description: 'Core Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: '/gifs/scissor-kick.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Test',
        description: 'Test Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: '/gifs/scissor-kick.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },

];

/* eslint-disable import/prefer-default-export */
export const stretchInfo = [
    {
        name: 'New Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'chest',
        equipmentNeeded: ['none'],
    },
    {
        name: 'New Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'chest',
        equipmentNeeded: ['none'],
    },
    {
        name: 'New Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'chest',
        equipmentNeeded: ['none'],
    },
    {
        name: 'New Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'chest',
        equipmentNeeded: ['none'],
    },
    {
        name: 'New Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'chest',
        equipmentNeeded: ['none'],
    },
    {
        name: 'New Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'New',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },

];
