/* eslint-disable import/prefer-default-export */

// back, core, stretching, neck

export const exerciseListL1 = [
    {
        name: 'Doorway Chest Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/doorway-pec-stretch/55571301-Standing-Chest-Stretch-against-Door_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '30 seconds - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Cat Cow 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cat-cow/45801301-Cat-Cow-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 1 set',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Thoracic Rotation 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/thoracic-rotation/42971301--Kneeling-Back-Rotation-Stretch-(female)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 reps each side - 1 set',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
        tip: '',
    },
    {
        name: 'High Plank 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/high-plank/51591301-Plank-on-Hands_Waist_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '30 second hold - 2 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: 'idk',
        tip: '',
    },
    {
        name: 'Glute Bridge 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/heel-glute-bridge/64351301-Heel-Glute-Bridge-(female)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 3 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: 'idk',
        tip: '',
    },
    {
        name: 'Face Pulls 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/band-face-pull/08961301-Band-face-pull_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'Same motion without a resistance band or weights',
        tip: 'Make sure you are squeezing your mid-back area',
    },
    {
        name: 'Prone Y Raise 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-y-raise/58221301-Prone-Y-Raise-(male)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Push Up Plus 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/push-up-plus/31451301-Push-Up-Plus_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'If it\'s too difficult, just focus on pushing through the floor to expand your back. Don\'t worry about doing the actual push-up portion.',
        tip: 'Keep your shoulders in place. Don\'t let them shrug up towards your ears.',
    },
    {
        name: 'Chin Tuck 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/chin-tuck/31491301-Chin-Tuck_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 2 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Prone Cervical Extension 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-cervical-extension/50601301-Prone-Cervical-Extension_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '6 reps - 2 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
];

// TODO
export const exerciseListL2 = [
    {
        name: 'Doorway Chest Stretch 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '30 seconds - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Cat Cow 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Hip Flexor Stretch 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '20 seconds/each leg - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Neck Circles 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: 'Each direction (left/right) 3 times',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Look Up/Down/Left/Right 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps each direction',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Thoracic Rotation 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 reps each side - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Bird Dogs 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '12 reps each side - 3 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Single Leg Glute Bridges',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Serratus Wall Slide',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Face Pulls',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '15 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Chin Tuck Raises - Laying Down',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 reps - 3 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Band Pull Aparts',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '12 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Prone Cervical Extension - Hold',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Push Up Plus',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Supermans',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '6 reps - 2 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Bear Crawls',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 2 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Bent Over Rows',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 2 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
];

// TODO
export const exerciseListL3 = [
    {
        name: 'Doorway Chest Stretch 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '30 seconds - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Cat Cow 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Hip Flexor Stretch 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '20 seconds/each leg - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Neck Circles 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: 'Each direction (left/right) 3 times',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Look Up/Down/Left/Right 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps each direction',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Thoracic Rotation 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 reps each side - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Bird Dogs',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '12 reps each side - 3 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Single Leg Glute Bridges',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '15 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Resistance Band Serratus Wall Slide',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Face Pulls',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '15 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Chin Tuck Raises - Laying Down',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 reps - 3 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Band Pull Aparts',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '20 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Push Up Plus',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '12 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Supermans',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 2 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Bear Crawls',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 2 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
    {
        name: 'Bent Over Rows',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '12 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'idk',
    },
];
