/* eslint-disable import/prefer-default-export */

// back, core, stretching, neck

export const exerciseListL1 = [
    {
        name: 'Doorway Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/doorway-pec-stretch/55571301-Standing-Chest-Stretch-against-Door_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '30 seconds - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Cat Cow',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cat-cow/45801301-Cat-Cow-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 reps - 1 set',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Thoracic Rotation',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/thoracic-rotation/42971301--Kneeling-Back-Rotation-Stretch-(female)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 reps each side - 1 set',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: 'idk',
        tip: '',
    },
    {
        name: 'High Plank',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/high-plank/51591301-Plank-on-Hands_Waist_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '30 second hold - 2 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: 'idk',
        tip: '',
    },
    {
        name: 'Glute Bridge',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/heel-glute-bridge/64351301-Heel-Glute-Bridge-(female)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 3 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: 'idk',
        tip: '',
    },
    {
        name: 'Face Pulls',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/band-face-pull/08961301-Band-face-pull_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'Same motion without a resistance band or weights',
        tip: 'Make sure you are squeezing your mid-back area',
    },
    {
        name: 'Prone Y Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/proe-y/58001301-Bodyweight-Lying-Prone-Ys_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Push Up Plus',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/push-up-plus/31451301-Push-Up-Plus_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'If it\'s too difficult, just focus on pushing through the floor to expand your back. Don\'t worry about doing the actual push-up portion.',
        tip: 'Keep your shoulders in place. Don\'t let them shrug up towards your ears.',
    },
    {
        name: 'Chin Tuck',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/chin-tuck/31491301-Chin-Tuck_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 2 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: 'You should feel this in the front of your neck.',
    },
    {
        name: 'Prone Cervical Extension',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-cervical-extension/50601301-Prone-Cervical-Extension_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '6 reps - 2 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
];

// TODO
export const exerciseListL2 = [
    {
        name: 'Chest Stretch - Kneeling',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/kneeling-chest-stretch/17851301-Kneeling-Chest-Stretch_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '30 seconds - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Cat Cow',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cat-cow/45801301-Cat-Cow-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 reps - 1 set',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Neck Circles',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/neck-circle/39941301-Neck-Circle-Stretch_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 each direction - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Bird Dogs',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bird-dog/12411301-Bird-Dog-male_Back-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 3 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: 'Try not to lean to one side or another. Keep your body centered and stable.',
    },
    {
        name: 'Single Leg Glute Bridge',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/single-leg-glute-bridge-female/60011301-Single-Straight-Leg-Glute-Bridge-Hold-(left)-(female)_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 2 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Face Pulls',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/band-face-pull/08961301-Band-face-pull_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '15 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: 'Try to increase the amount of resistance from Level 1.',
    },
    {
        name: 'Superman',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/superman-waist/08041301-Superman_Waist_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Scapular Push Up',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/scap-pushup/41171301-Kneeling-Scapular-Push-Up-(male)_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: 'Make sure you are pushing through the floor to get full upper back expansion.',
    },
    {
        name: 'Band Pull Aparts',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/band-pull-apart/45681301-Resistance-Band-Pull-Apart_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '12 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Standing Chin Tuck',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/chin-tuck/31491301-Chin-Tuck_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '8 reps - 3 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: 'Chin Tuck without resistance.',
        tip: 'Add a resistance band behind your head during your chin tuck to increase difficulty.',
    },
    {
        name: 'Prone Cervical Extension - Hold',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/prone-cercical-ext-hold/50611301-Prone-Cervical-Extension-Isometric-Hold_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '6 reps (5 sec. hold) - 2 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
];

// TODO
export const exerciseListL3 = [
    {
        name: 'Elbows Back Chest Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/elbows-back-stretch/46721301-Elbows-Back-Stretch-(male)_Chest_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '30 seconds - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Cat Cow',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/cat-cow/45801301-Cat-Cow-Stretch_Stretching_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '5 reps - 1 set',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Side Neck Stretch',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/side-neck-stretch/07131301-Side-Neck-Stretch_Neck-FIX_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '20 second hold each side - 2 sets',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Bear Crawls',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bear-crawl/33601301-Bear-Crawl_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 2 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: 'You can do these in-place or in an open area where you can crawl back and forth.',
        tip: 'Make sure you\'re pushing through the floor with your hands.',
    },
    {
        name: 'Plank Leg Lifts',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/front-plank-leg-lift/28961301-Front-Plank-with-Arm-and-Leg-Lift-(female)_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '45 second hold - 3 sets',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Around The World',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/around-the-world/49351301-Around-the-World-Superman_Hips_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '6 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Bent Over Rows',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/bent-over-rows/45701301-Resistance-Band-Bent-Over-Neutral-Grip-Row_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '12 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: 'You can do these with anything you can hold in two hands (barbell, water jugs, resistance bands, etc.)',
        tip: '',
    },
    {
        name: 'Serratus Wall Slides',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/serratus-wall-slide/50251301-Serratus-Wall-Slide_Back_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '10 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Band Pull Aparts',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/band-pull-apart/45681301-Resistance-Band-Pull-Apart_Shoulders_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '12 reps - 3 sets',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
        alternative: '',
        tip: '',
    },
    {
        name: 'Lying Chin Tuck - Raise',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://posturepal.s3.us-east-2.amazonaws.com/Gifs/lying-chin-tuck/50621301-Lying-Chin-Tucks_Neck_720.gif',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        reps: '6 reps (5 sec. hold) - 2 sets',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
        alternative: 'Lying Chin Tuck without raise',
        tip: '',
    },
];
