/* eslint-disable import/prefer-default-export */

// back, core, stretching, neck

export const exerciseListL1 = [
    {
        name: 'Chest Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Face Pulls 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'neck',
        equipmentNeeded: ['resistanceBands'],
    },
    {
        name: 'Dead Bugs 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bent Over Rows 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['weights'],
    },
    {
        name: 'Chin Tuck - Standing 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bird Dogs 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Planks 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Glute Bridges 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Wall Angels 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Band Pull Aparts 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['resistanceBands'],
    },
    {
        name: 'Shoulder Blade Squeezes 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Push Up Plus - Kneeling 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Isometric Rows 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Back of Head Resisted Extension - Standing 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Cat Cow 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Hip Flexor Stretch 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Circles 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        required: true,
        equipmentNeeded: ['none'],
    },
    {
        name: 'Look Up and Down, Left and Right 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        required: true,
        equipmentNeeded: ['none'],
    },
    {
        name: 'Thoracic Rotation 1',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        required: false,
        equipmentNeeded: ['none'],
    },
];

export const exerciseListL2 = [
    {
        name: 'Chest Stretch 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Face Pulls 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'neck',
        equipmentNeeded: ['resistanceBands'],
    },
    {
        name: 'Dead Bugs 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bent Over Rows 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['weights'],
    },
    {
        name: 'Chin Tuck - Standing 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bird Dogs 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Planks 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Glute Bridges 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Wall Angels 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Band Pull Aparts 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['resistanceBands'],
    },
    {
        name: 'Shoulder Blade Squeezes 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Push Up Plus - Kneeling 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Isometric Rows 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Back of Head Resisted Extension - Standing 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Cat Cow 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Hip Flexor Stretch 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Circles 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        required: true,
        equipmentNeeded: ['none'],
    },
    {
        name: 'Look Up and Down, Left and Right 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        required: true,
        equipmentNeeded: ['none'],
    },
    {
        name: 'Thoracic Rotation 2',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        required: false,
        equipmentNeeded: ['none'],
    },
];

export const exerciseListL3 = [
    {
        name: 'Chest Stretch 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        required: true,
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Face Pulls 3 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'neck',
        equipmentNeeded: ['resistanceBands'],
    },
    {
        name: 'Dead Bugs 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bent Over Rows 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['weights'],
    },
    {
        name: 'Chin Tuck - Standing 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Bird Dogs 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Planks 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Glute Bridges 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'core',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Wall Angels 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Band Pull Aparts 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['resistanceBands'],
    },
    {
        name: 'Shoulder Blade Squeezes 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Push Up Plus - Kneeling 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Isometric Rows 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'back',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Back of Head Resisted Extension - Standing 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'neck',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Cat Cow 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Hip Flexor Stretch 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        equipmentNeeded: ['none'],
    },
    {
        name: 'Neck Circles 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        required: true,
        equipmentNeeded: ['none'],
    },
    {
        name: 'Look Up and Down, Left and Right 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        required: true,
        equipmentNeeded: ['none'],
    },
    {
        name: 'Thoracic Rotation 3',
        description: 'Stand in a doorway with your arms bent at a 90-degree angle, forearms resting on the door frame. Lean forward until you feel a stretch in the front of your shoulders.',
        image: 'https://i.imgur.com/8JjUx9b.png',
        video: 'https://www.youtube.com/watch?v=OxXpWg9lSsE',
        muscleGroup: 'warmup',
        required: false,
        equipmentNeeded: ['none'],
    },
];
